name: Deploy to AWS
on:
  push:
    branches:
      - main
  # This workflow triggers on a push to the 'main' branch.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Match your local Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build --if-present

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        zip -r deploy.zip . -x "*.git*"
        aws s3 cp deploy.zip s3://my-eb-bucket-darey/deploy-${{ github.sha }}.zip
        aws elasticbeanstalk create-application-version --application-name my-node-app --version-label ${{ github.sha }} --source-bundle S3Bucket="my-eb-bucket-darey",S3Key="deploy-${{ github.sha }}.zip"
        aws elasticbeanstalk update-environment --application-name my-node-app --environment-name my-node-env --version-label ${{ github.sha }}
