name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Cleaner: uses just "v1.0.1" instead of "refs/tags/v1.0.1"
          release_name: Release ${{ github.ref_name }}
          draft: false  # Ensures the release is published, not a draft
          prerelease: false  # Marks it as a full release (adjust if needed)