name: Bump Version and Create Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v
          create_annotated_tag: true
          dry_run: true

      - name: Configure Git identity and push tag
        if: steps.bump.outputs.new_tag != ''
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git tag ${{ steps.bump.outputs.new_tag }} -a -m "Release ${{ steps.bump.outputs.new_tag }}"
          git push origin ${{ steps.bump.outputs.new_tag }}

      - name: Create Release
        if: steps.bump.outputs.new_tag != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          release_name: Release ${{ steps.bump.outputs.new_tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Debug tag creation
        run: |
          echo "New tag: ${{ steps.bump.outputs.new_tag }}"
          git tag -l